version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      checks:
        - '-QF1012' # disable the rule https://staticcheck.dev/docs/checks/#QF1012 comming from generated code
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
