// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_generic

import (
	"context"
	"github.com/conduktor/terraform-provider-conduktor/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GenericResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster": schema.StringAttribute{
				Optional:            true,
				Description:         "resource parent cluster (if any)",
				MarkdownDescription: "resource parent cluster (if any)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"kind": schema.StringAttribute{
				Required:            true,
				Description:         "resource kind",
				MarkdownDescription: "resource kind",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"manifest": schema.StringAttribute{
				CustomType:          customtypes.YAMLNormalizedType{},
				Required:            true,
				Description:         "resource manifest in yaml format. See [reference documentation](https://docs.conduktor.io/platform/reference/resource-reference/console/#manifests) for more details",
				MarkdownDescription: "resource manifest in yaml format. See [reference documentation](https://docs.conduktor.io/platform/reference/resource-reference/console/#manifests) for more details",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "resource name",
				MarkdownDescription: "resource name",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"version": schema.StringAttribute{
				Required:            true,
				Description:         "resource version",
				MarkdownDescription: "resource version",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

type GenericModel struct {
	Cluster  types.String               `tfsdk:"cluster"`
	Kind     types.String               `tfsdk:"kind"`
	Manifest customtypes.YAMLNormalized `tfsdk:"manifest"`
	Name     types.String               `tfsdk:"name"`
	Version  types.String               `tfsdk:"version"`
}
